config/routes.rb
Rails.application.routes.draw do
  get 'pricing/index'
  get 'pricing/weekly'
  get 'pricing/monthly'
  get 'pricing/fortnightly'
  get 'landing/cookie'




  resources :subscriptions
  devise_for :users
  post '/charges', controller: :subscriptions, action: :create
  get 'flowers/home'
  get 'landing/index'
  root controller: :landing, action: :index
  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]
  resources :pricing, only:[:index]
  resources :purchases, only: [:show]
  get 'flowers/new'
  post 'flowers/create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message
  include ActiveModel::Model
  attr_accessor :name, :email, :phone_number, :body
  validates :name, :email, :phone_number, :body, presence: true
end

app/models/plan.rb
class Plan < ApplicationRecord
end

app/models/purchase.rb
class Purchase < ApplicationRecord
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  validates :name, :address, :postcode, :mobile_number, :frequency, :size, :delivery, :start, presence: true
  # validates :mobile_number, numericality: {only_integer: true }, length: { minimum: 10, too_short: "is too short "}

  FREQUENCY = [['Weekly', 'week'], ['Fortnightly', '2 weeks'], ['Monthly', 'month']]
  SIZE = [['small', 3000], ['medium',5000], ["Large",8000], ["sublime", 11000]]
  DELIVERY = ['Thursday Delivery', 'Friday Delivery', 'Friday AM Collection', 'Friday PM collection']




  def process_payment
  customer_data = { card: card_token, plan: plan.sku}
  customer = Stripe::Customer.create customer_data

  Stripe::Charge.create customer: customer.id,
                        amount: @plan.price * 100,
                        description: plan.name,
                        currency: 'gbp'

end

  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flowers_controller.rb
class FlowersController < ApplicationController
    def new
      @message = Message.new
    end
  def create
      @message = Message.new message_params
  if @message.valid?
        MessageMailer.contact(@message).deliver_now
        redirect_to new_message_url
        flash[:notice] = "We have received your message and will be in touch soon!"
      else
        flash[:notice] = "There was an error sending your message. Please try again."
        render :new
      end
    end
  private
  def message_params
      params.require(:message).permit(:name, :email, :phone_number, :body)
    end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

class CookieController < ActionController::Base
  def cookie
    # put any code here that you need
    # (although for a static view you probably won't have any)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/controllers/pricing_controller.rb
class PricingController < ApplicationController
  def index
  end

  end

app/controllers/purchase_controller.rb
class PurchasesController < ApplicationController
	def show
		@purchase = Purchase.find_by_uuid(params[:id])
		@plan = Plan.find(@purchase.product_id)
	end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:new]

  def create
    Stripe.api_key = Rails.application.credentials.stripe_api_key

    plan_id = params[:plan_id]
    plan = Stripe::Plan.retrieve(plan_id)
    token = params[:stripeToken]

    customer = if current_user.stripe_id?
                Stripe::Customer.retrieve(current_user.stripe_id)
               else
                Stripe::Customer.create(email: current_user.email, source: token)
              end

    subscription = customer.subscriptions.create(plan: plan.id)

    options = {
      stripe_id: customer.id,
      stripe_subscription_id: subscription.id,
      subscribed: true
    }

    options.merge!(
      card_last4: params[:user][:card_last4],
      card_exp_month: params[:user][:card_exp_month],
      card_exp_year: params[:user][:card_exp_year],
      card_type: params[:user][:card_type]
    ) if params[:user][:card_last4]

    current_user.update(options)

    redirect_to root_path, notice: "Your subscription was setup successfully!"
  end

  def destroy
    customer = Stripe::Customer.retrieve(current_user.stripe_id)
    customer.subscriptions.retrieve(current_user.stripe_subscription_id).delete
    current_user.update(stripe_subscription_id: nil)
    current_user.subscribed = false

    redirect_to root_path, notice: "Your subscription has been cancelled."
  end
end

  # GET /subscriptions
  # GET /subscriptions.json
  # def index
  #   @subscriptions = Subscription.all
  # end
  #
  # # GET /subscriptions/1
  # # GET /subscriptions/1.json
  # def show
  # end
  #
  # # GET /subscriptions/new
  # def new
  #   @subscription = Subscription.new
  # end
  #
  # # GET /subscriptions/1/edit
  # def edit
  # end
  #
  # # POST /subscriptions
  # # POST /subscriptions.json
  # def create
  #      Stripe.api_key = Rails.application.credentials.stripe_api_key
  #
  #      plan_id = params[:plan_id]
  #      plan = Stripe::Plan.retrieve(plan_id)
  #      token = params[:stripeToken]
  #      email = params[:email]
  #
  #      customer = Stripe::Customer.create(email: email, source: token)
  #
  #      subscription = subscriptions.create(plan: plan.id)
  #
  #      options = {
  #        stripe_id: customer.id,
  #        stripe_subscription_id: subscription.id,
  #        subscribed: true
  #      }
  #
  #      options.merge!(
  #        card_last4: params[:user][:card_last4],
  #        card_exp_month: params[:user][:card_exp_month],
  #        card_exp_year: params[:user][:card_exp_year],
  #        card_type: params[:user][:card_type]
  #      ) if params[:user][:card_last4]
  #
  #      current_user.update(options)
  #
  #      redirect_to root_path, notice: "Your subscription was setup successfully!"
  #    end
  #   respond_to do |format|
  #     if @subscription.save
  #       format.html { redirect_to @subscription, notice: 'Subscription was successfully created.' }
  #       format.json { render :show, status: :created, location: @subscription }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @subscription.errors, status: :unprocessable_entity }
  #     end
  # end
  #
  # # PATCH/PUT /subscriptions/1
  # # PATCH/PUT /subscriptions/1.json
  # def update
  #   respond_to do |format|
  #     if @subscription.update(subscription_params)
  #       format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @subscription }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @subscription.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  #
  # # DELETE /subscriptions/1
  # # DELETE /subscriptions/1.json
  # def destroy
  #   @subscription.destroy
  #   respond_to do |format|
  #     format.html { redirect_to subscriptions_url, notice: 'Subscription was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end
  #
  # private
  #   # Use callbacks to share common setup or constraints between actions.
  #   def set_subscription
  #     @subscription = Subscription.find(params[:id])
  #   end
  #
  #   # Never trust parameters from the scary internet, only allow the white list through.
  #   def subscription_params
  #     params.require(:subscription).permit(:name, :address, :postcode, :mobile_number, :deliverAddress, :deliverName, :frequency, :size, :delivery, :start)
  #   end
  # end

app/controllers/weekly_controller.rb
class WeeklyController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/flowers/home.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>Francis Smith</title>
  </head>

  <body id="bgrnd">
    <%= render 'nav' %>
    <%= render 'mailingform' %>


<div class="wrapper">
  <%= render 'about' %>
  <%= render 'subscription' %>
</div>

<div class="instagram">
  <p>Our Floral Gallery</p>

  <!-- LightWidget WIDGET --><script src="https://cdn.lightwidget.com/widgets/lightwidget.js"></script><iframe src="https://cdn.lightwidget.com/widgets/ddeece40868056008b8a415a79ea5e64.html" scrolling="no" allowtransparency="true" class="lightwidget-widget" style="width:70%;border:0;overflow:hidden;"></iframe>
</div>

<div class="contact">


<%= render 'wellbeing' %>
<div class="contactus">
  <h1>Contact Us</h1>
  </div>

<div class="typeform-widget" data-url="https://larathordardottir.typeform.com/to/wQYHIG" style="width: 100%; height: 500px;"></div> <script> (function() { var qs,js,q,s,d=document, gi=d.getElementById, ce=d.createElement, gt=d.getElementsByTagName, id="typef_orm", b="https://embed.typeform.com/"; if(!gi.call(d,id)) { js=ce.call(d,"script"); js.id=id; js.src=b+"embed.js"; q=gt.call(d,"script")[0]; q.parentNode.insertBefore(js,q) } })() </script> <div style="font-family: Sans-Serif;font-size: 12px;color: #999;opacity: 0.5; padding-top: 5px;"> powered by <a href="https://admin.typeform.com/signup?utm_campaign=wQYHIG&utm_source=typeform.com-12654766-Basic&utm_medium=typeform&utm_content=typeform-embedded-poweredbytypeform&utm_term=EN" style="color: #999" target="_blank">Typeform</a> </div>





<script src="https://apps.elfsight.com/p/platform.js" defer></script>
<div class="elfsight-app-f5a734bb-76bc-42a7-a1fc-09b9e5ca4b89"></div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/landing/_about.html.erb
<div class="workshop">
  <%= image_tag("aboutus.jpg", :alt => "flower workshop", :class => 'worksop_photo') %>
</div>

<div class="card" id="aboutUs">
  <span id="anchor1" class="anchor"></span>
  <div class="card-body">
    <h1> Francis Smith <br /> <span class="meaning"> -flowers with meaning -</span> </h1>
    <br>
    <p>
Once upon a time in the wild wild west of London, Lizzie used to frequent her local
Italian restaurant after a long day at work, managing musicians. As a flower fanatic,
she’d often remark on the beautiful displays inside. When Philippa confided that not
only did, she run restaurants brilliantly but also created discussion worthy flowers,
their fate was sealed; the conversation instantly turned from pizzas to peonies. </p>
<br>
<br>
<p class="quoteee">“Nature is not matter only, she is also spirit”</p>
<p class="name">- Carl Jung</p>
<br>
<p>

  Francis Smith was selfishly borne out of a desperation for floral sublimity in
  Brackenbury Village. Our workshop was created to share our vision and exquisite flowers with likeminded neighbours. We believe in celebrating the magical language & beauty of flowers and their symbolism; love, passion, healing, apology & joy are just five of many reasons to have or gift flowers. In an overly digitised world, the art of retail interaction is often lost behind a screen or an impersonal cardboard package. Our heart and soul is in bringing flowers to our community and sharing our passion with our customers. We also delivery by bicycle or by foot, wherever
  possible, as being ecologically minded for us in no longer an option but a
  necessity.
  </div>
</div>



<div class="card" id="photos">
  <div class="pics">
    <%= image_tag("lizzie.png", :alt => "flower workshop", :class => 'bouquet') %>
  </div>
</div>

app/views/landing/_footer.html.erb
<footer class="footer">
  <div class="container-fluid bg py-3" id="footer">
    <div class="container">
      <div class="row">
              <div class="col-sm">
                <h4>Contact us:</h4>
                <p><a class="social" href="tel:07837585786">0783785786</a></p>
                <p>For Flowers:</p>
                <p><a class="social" href="mailto:contact@francissmithflowers.com">contact@francissmithflowers.com</a></p>
                <p>For Wellness:</p>
                <p><a class="social" href="mailto:contact@minusoneworkshop.com">contact@minusoneworkshop.com</a></p>
              </div>
              <div class="col-sm">
              <h4>Be Social:</h4>
              <p><%= link_to image_tag("instagram.png"), "https://www.instagram.com/francissmithflowers/"%></p>
              <p><a class="social" href="https://www.instagram.com/francissmithflowers/">@FrancisSmithFlowers</a></p>
              <p><%= link_to image_tag("facebook1.png"), "https://www.facebook.com/francissmithflowers/"%></p>
              <p><a class="social" href="https://www.facebook.com/francissmithflowers/">@FrancisSmith</a></p>
              <p><%= link_to image_tag("pinterest.png"), "https://www.pinterest.com/francissmithflowers/"%></p>
              <p><a class="social" href="https://www.pinterest.com/francissmithflowers/">@FrancisSmithFlowers</a></p>
              </div>
              <div class="col-sm">
              <h4>Stay in Touch:</h4>
              <p>If you are a flower-fan and would like to be the first to know
                about everything Francis Smith please join our mailing list.</p>
                <!-- Begin Mailchimp Signup Form -->
                <link href="//cdn-images.mailchimp.com/embedcode/classic-10_7.css" rel="stylesheet" type="text/css">
                <style type="text/css">
                	#mc-embedded-subscribe-form input[type=checkbox]{display: inline; width: auto;margin-right: 10px;}
                	#mergeRow-gdpr {margin-top: 20px;}
                	#mergeRow-gdpr fieldset label {font-weight: normal;}
                	#mc-embedded-subscribe-form .mc_fieldset{border:none;min-height: 0px;padding-bottom:0px;}
                </style>
                <div id="mc_embed_signup">
                <form action="https://francissmithflowers.us19.list-manage.com/subscribe/post?u=36c25608556fa12090c910bbf&amp;id=a8609d32b6" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
                    <div id="mc_embed_signup_scroll">
                <div class="mc-field-group">
                	<label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
                </label>
                	<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
                </div>
                <div class="mc-field-group">
                	<label for="mce-FNAME">First Name  <span class="asterisk">*</span>
                </label>
                	<input type="text" value="" name="FNAME" class="required" id="mce-FNAME">
                </div>
                <div class="mc-field-group">
                	<label for="mce-LNAME">Last Name  <span class="asterisk">*</span>
                </label>
                	<input type="text" value="" name="LNAME" class="required" id="mce-LNAME">
                </div>
                <div class="mc-field-group size1of2">
                	<label for="mce-MMERGE6-month">Birthday </label>
                	<div class="datefield">
                		<span class="subfield monthfield"><input class="birthday " type="text" pattern="[0-9]*" value="" placeholder="MM" size="2" maxlength="2" name="MMERGE6[month]" id="mce-MMERGE6-month"></span> /
                		<span class="subfield dayfield"><input class="birthday " type="text" pattern="[0-9]*" value="" placeholder="DD" size="2" maxlength="2" name="MMERGE6[day]" id="mce-MMERGE6-day"></span>
                		<span class="small-meta nowrap">( mm / dd )</span>
                	</div>
                </div><div id="mergeRow-gdpr" class="mergeRow gdpr-mergeRow content__gdprBlock mc-field-group">
                    <div class="content__gdpr">
                        <label>Marketing Permissions</label>
                        <p>Please select all the ways you would like to hear from Francis Smith Flowers:</p>
                        <fieldset class="mc_fieldset gdprRequired mc-field-group" name="interestgroup_field">
                		<label class="checkbox subfield" for="gdpr_2095"><input type="checkbox" id="gdpr_2095" name="gdpr[2095]" value="Y" class="av-checkbox gdpr"><span>Email</span> </label>
                        </fieldset>
                        <p>You can unsubscribe at any time by clicking the link in the footer of our emails. For information about our privacy practices, please visit our website.</p>
                    </div>
                    <div class="content__gdprLegal">
                        <p>We use Mailchimp as our marketing platform. By clicking below to subscribe, you acknowledge that your information will be transferred to Mailchimp for processing. <a href="https://mailchimp.com/legal/" target="_blank">Learn more about Mailchimp's privacy practices here.</a></p>
                    </div>
                </div>
                	<div id="mce-responses" class="clear">
                		<div class="response" id="mce-error-response" style="display:none"></div>
                		<div class="response" id="mce-success-response" style="display:none"></div>
                	</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_36c25608556fa12090c910bbf_a8609d32b6" tabindex="-1" value=""></div>
                    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
                    </div>
                </form>
                </div>
                <script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';fnames[3]='ADDRESS';ftypes[3]='address';fnames[4]='PHONE';ftypes[4]='phone';fnames[6]='MMERGE6';ftypes[6]='birthday';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
                <!--End mc_embed_signup-->
              </div>
            </div>
        </div>
        </div>
      </div>
      </div>
      <div class="container"id="footer">
          <div class="row">
              <div class="col align-self-start">
            <p class="left"><a class="social" href="landing/cookie">Read our cookie policy</a></p>
            <p class="left">©Francis Smith Flowers Ltd 2019</p>
          </div>
          <div class="col-sm">
          </div>
          </div>
      </div>
</footer>

app/views/landing/_subscription.html.erb
<div class="subscription" id="repeatPrescription">
  <span id="hello" class="hey">  </span>
    <div class="content">


  <h1>Flowers with meaning </h1>
  <br>
  <p class="meaning">“Can we speak in flowers, it will be easier to understand."</p>
    <br>
  <p>
 From our Brackenbury Village workshop, we are here to fulfil your floral desires
 from as small as a delicate jam jar, to a special birthday or a breath-taking
 wedding; we would love to talk flowers with you for all and any occasions. <br> <br>To Order
 flowers, call us on 07837585786 or drop us an email with some details…</p>
<br>
<div class="call">
  <a href="tel:07837585786" id="callButtons" class="btn btn-info btn-sm " role="button">Call us</a>
  <a href="mailto:contact@francissmithflowers.com" id="callButtons" class="btn btn-info btn-sm " role="button">Email us</a>
</div>
  <br>
<br>
<h2 class="title2">Flower Subscriptions </h2>
<br>
<p>We wholeheartedly believe that receiving a weekly bunch of beautiful fresh
flowers is life enhancing and a wonderful way to bring nature into our lives & homes;
it should be one of the weekly rituals we partake in to make us all feel
better.</p>
<p>Each week our gorgeous seasonal blooms will not only look stunning but
will feature flowers aligning to our monthly affirmations blog, which goes deeper
 into the symbolism & healing properties of the flowers we love so much.</p>
<br>
  <%= link_to '<button type="button" class="btn btn-lg" id="subscriptionButton">Buy or gift a floral subscription</button>'.html_safe, pricing_index_path %>
</div>
    </div>

app/views/pricing/_buttons.html.erb
<br>
<div class="Subscription_buttons">
    <div class="col align-self-center">
<%= link_to '  <button type="button" class="btn btn-light">Weekly Flowers</button>'.html_safe, pricing_weekly_path %>
  <br>
  <%= link_to '  <button type="button" class="btn btn-light">Fortnightly Flowers</button>'.html_safe, pricing_fortnightly_path %>
  <br>
  <%= link_to '  <button type="button" class="btn btn-light">Monthly Flowers</button>'.html_safe, pricing_monthly_path %>
</div>

</div>

app/views/subscriptions/edit.html.erb
<h1>Editing Subscription</h1>

<%= render 'form', subscription: @subscription %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subscriptions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Postcode</th>
      <th>Mobile number</th>
      <th>Deliveraddress</th>
      <th>Delivername</th>
      <th>Frequency</th>
      <th>Size</th>
      <th>Delivery</th>
      <th>Start</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subscriptions.each do |subscription| %>
      <tr>
        <td><%= subscription.name %></td>
        <td><%= subscription.address %></td>
        <td><%= subscription.postcode %></td>
        <td><%= subscription.mobile_number %></td>
        <td><%= subscription.deliverAddress %></td>
        <td><%= subscription.deliverName %></td>
        <td><%= subscription.frequency %></td>
        <td><%= subscription.size %></td>
        <td><%= subscription.delivery %></td>
        <td><%= subscription.start %></td>
        <td><%= link_to 'Show', subscription %></td>
        <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
        <td><%= link_to 'Destroy', subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subscription', new_subscription_path %>

app/views/subscriptions/new.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
   <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
   <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   <%= javascript_include_tag 'application', 'https://js.stripe.com/v3/','data-turbolinks-track': 'reload' %>
   <%= tag :meta, name: "stripe-key", content: Rails.application.credentials.stripe_publishable_key %>
  </head>
<body>


<h1>New Subscription</h1>

<div class="form">
<%= render 'form', subscription: @subscription %>
</div>


<%= link_to 'Back', subscriptions_path %>

<script type="text/javascript">
// Create a Stripe client.
var stripe = Stripe('pk_test_lxheG7wkpQA038p5HCyemKKy');

// Create an instance of Elements.
var elements = stripe.elements();

// Custom styling can be passed to options when creating an Element.
// (Note that this demo uses a wider set of styles than the guide below.)
var style = {
  base: {
    color: '#32325d',
    lineHeight: '18px',
    fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
    fontSmoothing: 'antialiased',
    fontSize: '16px',
    '::placeholder': {
      color: '#aab7c4'
    }
  },
  invalid: {
    color: '#fa755a',
    iconColor: '#fa755a'
  }
};

// Create an instance of the card Element.
var card = elements.create('card', {style: style});

// Add an instance of the card Element into the `card-element` <div>.
card.mount('#card-element');

// Handle real-time validation errors from the card Element.
card.addEventListener('change', function(event) {
  var displayError = document.getElementById('card-errors');
  if (event.error) {
    displayError.textContent = event.error.message;
  } else {
    displayError.textContent = '';
  }
});

// Handle form submission.
var form = document.getElementById('payment-form');
form.addEventListener('submit', function(event) {
  event.preventDefault();

  stripe.createToken(card).then(function(result) {
    if (result.error) {
      // Inform the user if there was an error.
      var errorElement = document.getElementById('card-errors');
      errorElement.textContent = result.error.message;
    } else {
      // Send the token to your server.
      stripeTokenHandler(result.token);
    }
  });
});
</script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://js.stripe.com/v3/"></script>

  </body>
</html>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @subscription.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @subscription.address %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @subscription.postcode %>
</p>

<p>
  <strong>Mobile number:</strong>
  <%= @subscription.mobile_number %>
</p>

<p>
  <strong>Deliveraddress:</strong>
  <%= @subscription.deliverAddress %>
</p>

<p>
  <strong>Delivername:</strong>
  <%= @subscription.deliverName %>
</p>

<p>
  <strong>Frequency:</strong>
  <%= @subscription.frequency %>
</p>

<p>
  <strong>Size:</strong>
  <%= @subscription.size %>
</p>

<p>
  <strong>Delivery:</strong>
  <%= @subscription.delivery %>
</p>

<p>
  <strong>Start:</strong>
  <%= @subscription.start %>
</p>

<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>